name: merchant_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.7.0
  injectable: ^2.4.4
  uuid: ^4.5.1
  internet_connection_checker_plus: ^2.5.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  mocktail: ^1.0.4 
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true




























  #


